# Generated by Django 5.1.15 on 2026-04-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0004_driver_route_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driverprofile",
            name="account_id",
        ),
    ]
